### ISSUE TITLE
Sync and Ping no longer working after upgrade to 2.1.0

### ISSUE THREAD

**Issue by jmarass** [U-CRM/billing#76]
Since upgrading to 2.1.0 (I am now at 2.1.2 with the same issue) I cannot get any devices to sync.  Also, it is not showing any ping statistics and as a result shows the device is down.  If I add it through the "Add Device" option, there is nowhere to enter the IP address and so I am forced to go manually add an interface with the IP.  If I go this route, nothing works.  If I delete the device completely and then use "Quick Add Device" I can at least get the ping statistics but sync still does not work.  There is nothing in the logs to indicate why.

**Comment by keksa** [comment]
Hello, can you please try it in 2.1.3? We fixed a lot of errors around this.

**Comment by jmarass** [comment]
I have upgraded and I am still unable to sync. The logs at least now show that UCRM is "connecting" to my devices but there is never an indication that it successfully connects. I deleted a device and added it back fresh to see if that would help but no luck.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jmarass** [comment]
I am attaching my logs to see if you can identify the issue.  On a positive note, I am seeing logs now after attempting to sync but there are a lot of failures.

[prod.txt](https://github.com/U-CRM/billing/files/534088/prod.txt)

**Comment by jmarass** [comment]
I wanted to update you that I have gone through the process of starting from scratch to determine if the issue is software or somehow data related.  I blew away the entire UCRM and built it from scratch using the 2.1.3 version.  I have confirmed that the sync issue is still present after doing so.  It appears that the sync app has flaws that are preventing it from working correctly.  I can confirm that it appears in the logs that UCRM is successfully logging into my devices using SSH over port 20 (we change the port) and I can also confirm that the logs on my Access Points also show successful connections.  However, no useful data is being pulled down from the devices.

**Comment by jmarass** [comment]
Could it be possible that firewall rules are preventing the sync from working correctly?  Can you tell me what ports UCRM-billing needs open from the source and destination side in order to sync correctly?  Does the sync solely use SSH or is SNMP involved?

**Comment by keksa** [comment]
Hello @jmarass, the UCRM uses only SSH for connection as of now. SNMP is not used in any way. Did you try this in 2.1.4? We fixed some problems with EdgeOS synchronization there.

**Comment by jmarass** [comment]
I just installed it and I am still experiencing the same issues.  However, I do see a new event in the prod.log that may be of some assistance.  Let me know if this means anything to you:

[2016-10-19 02:10:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET //admin/config.php"" at /usr/src/ucrm/app/cache/prod/classes.php line 2797 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET //admin/config.php\" at /usr/src/ucrm/app/cache/prod/classes.php:2797, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /usr/src/ucrm/app/cache/prod/appProdUrlMatcher.php:3644)"} []

**Comment by keksa** [comment]
@jmarass This is just someone trying to hack your system and not finding anything at /admin/config.php URL. :)
Would it be possible to provide us with SSH access to your UCRM server and web interface account? If so, please contact me at ondrej.exner@ubnt.com

**Comment by jmarass** [comment]
I just emailed you.  Let me know if you receive it.
